### ISSUE TITLE
開源專案的使用困境是甚麼？怎麼讓更多人使用

### ISSUE THREAD

**Issue by Rnyfdc** [ycku/pitches#2]
因為我當時聽老師介紹時覺得這是很不錯的共享筆記專案，但是似乎參與者不多，請問有甚麼方法可以解決？
是否應該增加更多誘因呢？或是大家對於此平台的使用方式不夠明瞭？

**Comment by ycku** [comment]
不好意思, 我似乎遺漏了這個問題. 請問你後來還有嘗試使用嗎?
參與者並不是不多, 只是你還沒有遇到而已.
試著參與開源社群的活動, 你就會在同好之間找到誘因的.

**Comment by Rnyfdc** [comment]
我後來有嘗試使用
我覺得是我沒有遇到參與者
謝謝老師
