### ISSUE TITLE
請問如果想使用Github作為履歷，在內容上有沒有什麼樣的建議？

### ISSUE THREAD

**Issue by chiaya710623** [ycku/pitches#3]
想了解如果想把Github作為履歷使用，什麼樣的內容比較適合放上Github。
Github是不是就不太適合放平時練習的小程式？

**Comment by ycku** [comment]
只要你願意, 基本上都適合放上github.
履歷重點是讓別人清楚瞭解你的專案說明, 表現你的專業態度.

練習用的程式可以獨立開專案來做,
和有計畫性發展的專案有所區別就好.
每一個練習, 都可能是一個創意萌發的起點呢!

**Comment by chiaya710623** [comment]
謝謝老師的解答：）
